'use strict';
const byId=id=>document.getElementById(id);
let mode='login';
const notice=text=>{byId('account-notice').textContent=text;};
async function api(path,body){const response=await fetch('/nexus-api'+path,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});let data;try{data=await response.json();}catch{throw Error('The account service is unavailable. Please try again shortly.');}if(!response.ok)throw Error(data.error||'Could not complete that request.');return data;}
async function load(){
 try{const state=await api('/account');byId('auth-panel').hidden=!!state.user;byId('session-panel').hidden=!state.user;
 byId('member-name').textContent=state.user?`Signed in as ${state.user.username}`:'';byId('connections').replaceChildren();
 for(const provider of state.providers){const card=document.createElement('article');card.className='panel';const title=document.createElement('h3');title.textContent=provider.label;const status=document.createElement('strong');status.textContent=provider.connection?`Authorized as ${provider.connection.name}`:provider.configured?'Ready to authorize':'Setup required';const description=document.createElement('p');description.textContent=provider.capability;const detail=document.createElement('p');detail.className='small';detail.textContent=provider.configured?'Authorization is separate from inbox sync and message sending.':'The Guild needs to register this provider’s developer app before you can connect. No access has been granted.';
 const button=document.createElement('button');button.type='button';button.textContent=provider.connection?'Disconnect':!provider.configured?'Awaiting provider setup':state.user?`Authorize ${provider.label}`:'Sign in to connect';button.disabled=!state.user||(!provider.configured&&!provider.connection);
 button.addEventListener('click',async()=>{button.disabled=true;try{if(provider.connection){const data=await api(`/connections/${provider.id}/disconnect`,{});await load();notice(data.message);}else{const data=await api(`/connections/${provider.id}/start`,{});window.location.assign(data.url);}}catch(error){notice(error.message);button.disabled=false;}});
 card.append(title,status,description,detail,button);byId('connections').append(card);
 }
 return state;
 }catch(error){notice(error.message);byId('auth-panel').hidden=true;return null;}
}
for(const button of document.querySelectorAll('[data-mode]'))button.addEventListener('click',()=>{mode=button.dataset.mode;for(const b of document.querySelectorAll('[data-mode]'))b.setAttribute('aria-pressed',String(b===button));byId('recovery-field').hidden=mode!=='recover';byId('recovery-code').required=mode==='recover';byId('password').autocomplete=mode==='login'?'current-password':'new-password';byId('password-label').textContent=mode==='recover'?'New password':'Password';byId('auth-submit').textContent=mode==='register'?'Create account ↗':mode==='recover'?'Reset password ↗':'Sign in ↗';byId('auth-help').textContent=mode==='register'?'Use at least 12 characters. You’ll receive a recovery code to save securely.':mode==='recover'?'Enter the recovery code you saved when creating your account. Resetting signs out all existing sessions.':'Use the username and password you created for Nexus.';});
byId('auth-form').addEventListener('submit',async event=>{event.preventDefault();const button=byId('auth-submit');button.disabled=true;try{const data=await api('/auth/'+mode,{username:byId('username').value,password:byId('password').value,recoveryCode:byId('recovery-code').value});byId('password').value='';byId('recovery-code').value='';await load();if(data.recoveryCode){byId('new-recovery').textContent=data.recoveryCode;byId('recovery-panel').hidden=false;}notice(mode==='register'?'Your Nexus account is ready. Save your recovery code below.':mode==='recover'?'Password reset. Save your new recovery code.':'You’re signed in.');}catch(error){notice(error.message);}finally{button.disabled=false;}});
byId('recovery-saved').addEventListener('click',()=>{byId('new-recovery').textContent='';byId('recovery-panel').hidden=true;});
byId('logout').addEventListener('click',async()=>{const button=byId('logout');button.disabled=true;try{await api('/auth/logout',{});byId('new-recovery').textContent='';byId('recovery-panel').hidden=true;await load();notice('Signed out. Browser-saved workspace notes remain on this device.');}catch(error){notice(error.message);}finally{button.disabled=false;}});
const result=new URLSearchParams(location.search).get('connection');
load().then(state=>{if(!state)return;notice(result==='connected'?'Account authorization saved. Inbox sync and sending remain unavailable.':result==='failed'?'Authorization was not completed. Please retry from the connection card.':state.user?'Manage your platform permissions below.':'Sign in or create your Nexus account to get started.');if(result)history.replaceState(null,'',location.pathname);});
