'use strict';
(()=>{
 const el=id=>document.getElementById(id), make=(tag,text,cls)=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;};
 let apps=[],member=null,current='followups',selected={messages:null,meetings:null},generation={messages:0,meetings:0};
 const symbols={gmail:'M',calendar:'31',calendly:'C',telegram:'↗',slack:'#',linkedin:'in'};
 const say=text=>el('dashboard-notice').textContent=text;
 async function api(path,body){const r=await fetch('/nexus-api/apps'+path,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(60000)});let d;try{d=await r.json();}catch{throw Error('Connections are temporarily unavailable. Please retry.');}if(!r.ok)throw Error(d.error||'Could not load this app.');return d;}
 const action=(label,fn)=>{const b=make('button',label);b.type='button';b.addEventListener('click',fn);return b;};
 function view(id){if(!['followups','messages','meetings','apps'].includes(id))id='followups';current=id;for(const n of document.querySelectorAll('[data-page]'))n.hidden=n.dataset.page!==id;for(const n of document.querySelectorAll('[data-view]'))n.setAttribute('aria-current',n.dataset.view===id?'page':'false');el('view-title').textContent={followups:'Your follow-ups',messages:'Messages',meetings:'Meetings',apps:'Connected apps'}[id];history.replaceState(null,'',location.pathname+'#'+id);if(id==='messages'||id==='meetings')sources(id);}
 for(const n of document.querySelectorAll('[data-view]'))n.addEventListener('click',()=>view(n.dataset.view));
 el('new-follow-up').addEventListener('click',()=>{view('followups');el('prompt').focus();});
 window.addEventListener('hashchange',()=>view(location.hash.slice(1)));
 function empty(target,title,text,buttonText='Connect an app',fn=()=>view('apps')){const box=make('div','','empty');box.append(make('h2',title),make('p',text),action(buttonText,fn));target.replaceChildren(box);}
 function sources(kind){const target=el(kind==='messages'?'message-sources':'meeting-sources'),items=el(kind==='messages'?'message-items':'meeting-items');target.replaceChildren();const list=apps.filter(a=>a.kind===kind&&a.connection);if(!list.length){el('refresh-'+kind).hidden=true;el(kind+'-detail').textContent='';empty(items,kind==='messages'?'Your conversations start here.':'Your meetings, in one place.',member?'Connect '+(kind==='messages'?'Gmail, Telegram, Slack, or LinkedIn.':'Google Calendar or Calendly.'):'Sign in to connect your apps. Your conversations are only loaded when you select an app.',member?'View connected apps':'Sign in',()=>member?view('apps'):location.assign('/account'));return;}
 for(const a of list){const b=action(a.label,()=>loadItems(kind,a.id));b.setAttribute('aria-pressed',String(selected[kind]===a.id));target.append(b);}if(!selected[kind]||!list.some(a=>a.id===selected[kind])){selected[kind]=null;empty(items,'Choose an app above.','Load recent context when you need it. Nothing is sent from this screen.','Manage apps',()=>view('apps'));}}
 async function loadItems(kind,id,channel){selected[kind]=id;const version=++generation[kind];sources(kind);const target=el(kind==='messages'?'message-items':'meeting-items'),refresh=el('refresh-'+kind),detail=el(kind+'-detail');refresh.hidden=false;refresh.disabled=true;target.replaceChildren(make('p','Loading recent context…'));detail.textContent='';try{const d=await api('/'+id+'/items'+(channel?'?channel='+encodeURIComponent(channel):''));if(version!==generation[kind])return;target.replaceChildren();detail.textContent='Loaded '+new Date(d.loadedAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})+(d.more?' · Recent items only; more available in the original app.':' · Refresh to check for updates.');if(!d.items.length)empty(target,'Nothing to show yet.','No recent items were returned by this app.','Refresh',()=>loadItems(kind,id,channel));for(const item of d.items){const card=make('article','','context-item');card.append(make('span',apps.find(a=>a.id===id)?.label,'badge'),make('h3',item.title));if(item.person)card.append(make('p',item.person,'small'));if(item.date){const date=new Date(item.date);if(!isNaN(date))card.append(make('p',date.toLocaleString(),'small'));}card.append(make('p',item.text||''));const actions=make('div','','actions');if(item.channel)actions.append(action('Open conversation',()=>loadItems(kind,id,item.channel)));else{actions.append(action('Create follow-up',()=>{view('followups');el('prompt').value=[item.title,item.person,item.date,item.text].filter(Boolean).join('\n');openReview({source:el('prompt').value,title:'Follow up: '+item.title,person:item.person||'',draft:''});}));try{const url=new URL(item.url);if(url.protocol==='https:'){const a=make('a','Open original ↗','button');a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';actions.append(a);}}catch{}}
 card.append(actions);target.append(card);}}catch(e){if(version!==generation[kind])return;empty(target,'This app couldn’t load.',e.message,'Try again',()=>loadItems(kind,id,channel));}finally{if(version===generation[kind]){refresh.disabled=false;refresh.onclick=()=>loadItems(kind,id,channel);}}}
 async function load(){el('retry-apps').hidden=false;el('retry-apps').textContent='Refresh connections';try{const d=await api('');say('');apps=d.apps;member=d.user;el('connected-count').textContent=String(apps.filter(a=>a.connection).length);el('dashboard-account').textContent=member?member.username+' · Account →':'Sign in to connect apps →';el('connection-summary').replaceChildren(make('span',member?`${apps.filter(a=>a.connection).length} of ${apps.length} apps connected. Choose where to begin.`:'Sign in once, then choose the apps you want to connect.'));if(!member){const a=make('a','Sign in →');a.href='/account';el('connection-summary').append(a);}el('apps-grid').replaceChildren();for(const a of apps){const card=make('article','','app-card'),top=make('div','','app-top');top.append(make('span',symbols[a.id],'app-symbol'),make('h2',a.label));card.append(top,make('p',a.description),make('span',a.connection?'Connected · '+a.connection.name:a.configured?'Ready to connect':'Setup in progress','app-status'+(a.connection?' connected':'')));const details=make('details');details.append(make('summary','What happens when I connect?'),make('p',a.configured?(a.id==='telegram'||a.id==='linkedin'?'Unipile handles account authorization. Nexus loads recent chats and messages on request. Open the original app to reply.':'You approve read access at the provider. Nexus loads recent context when requested. Sending is not enabled.'):a.setup));card.append(details);const b=action(a.connection?'Disconnect':!member?'Sign in to connect':a.configured?'Connect '+a.label:'Awaiting setup',async()=>{if(!member){location.assign('/account');return;}b.disabled=true;try{if(a.connection){await api('/'+a.id+'/disconnect',{});for(const k of ['messages','meetings']){generation[k]++;selected[k]=null;el(k==='messages'?'message-items':'meeting-items').replaceChildren();}await load();say(a.label+' disconnected. Existing follow-up drafts stay in your browser. You can also revoke access in the provider’s settings.');}else{const d=await api('/'+a.id+'/connect',{});location.assign(d.url);}}catch(e){say(e.message);b.disabled=false;}});b.disabled=!!member&&!a.configured&&!a.connection;card.append(b);el('apps-grid').append(card);}if(current==='messages'||current==='meetings')sources(current);}
 catch(e){say(e.message);el('retry-apps').hidden=false;el('connection-summary').textContent='Unable to check connections.';}}
 el('retry-apps').addEventListener('click',load);
 const result=new URLSearchParams(location.search).get('connection');if(result)say(result==='connected'?'App connected. Choose Messages or Meetings to load context.':result==='pending'?'Finishing authorization. Refresh connections in a moment.':'Connection wasn’t completed. You can try again.');view(location.hash.slice(1));load();
})();
