'use strict';
(()=>{
 const $=id=>document.getElementById(id),key='nexus-routine-drafts-v1';
 const apps={gmail:'Gmail',calendar:'Google Calendar',calendly:'Calendly',telegram:'Telegram',slack:'Slack',linkedin:'LinkedIn'};
 const templates=[
 ['Who needs a reply?','Start the day with the conversations that need you.','Review recent messages and open commitments. Identify conversations awaiting my reply, explain why each matters, and suggest a short follow-up for my review. Do not invent commitments or send anything.',['gmail','telegram'],'weekdays','09:00','↗'],
 ['Prepare for your calls','Walk into your next call with the context in hand.','Review upcoming meetings and relevant conversations. Prepare a brief with the people involved, previous commitments, and questions to ask. Cite the source of each point and flag missing context.',['calendar','calendly'],'weekdays','08:30','▦'],
 ['Follow up after an event','Keep the people you met and promises you made in view.','Review the event notes I provide. Identify each person I met, what we discussed, and any explicit next step. Prepare a personal follow-up for my review. Ask about missing details. Do not infer attendance from an invitation.',['telegram','linkedin'],'weekly','10:00','◎'],
 ['Reconnect this week','Notice the important conversations that went quiet.','Review the business conversations I select. Surface unanswered questions and explicit commitments still open. Suggest who to follow up with and why, using evidence rather than assuming someone is interested.',['gmail','telegram','linkedin'],'weekly','15:00','↻'],
 ['Sort out your inbox','Review your inbox and prepare thoughtful replies.','Review recent email. Highlight messages that need my response and prepare concise reply suggestions with their supporting context. Separate explicit deadlines from suggested dates. Do not send messages.',['gmail'],'daily','09:00','✉'],
 ['Catch up with your team','Find requests and decisions across your team conversations.','Review my selected Slack conversations. Summarize decisions, direct requests, and commitments involving me. Include source context and suggest replies for review. Distinguish discussion from agreed action.',['slack'],'weekdays','09:00','#']
 ];
 let drafts=[],editing=null;
 const n=(tag,text,cls)=>{const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e;};
 const b=(text,fn)=>{const e=n('button',text);e.type='button';e.addEventListener('click',fn);return e;};
 const valid=d=>d&&typeof d.id==='string'&&typeof d.name==='string'&&d.name.length<=100&&typeof d.prompt==='string'&&d.prompt.length<=6000&&Array.isArray(d.apps)&&d.apps.every(a=>Object.hasOwn(apps,a))&&['daily','weekdays','weekly'].includes(d.frequency)&&/^[0-6]$/.test(d.day)&&/^([01]\d|2[0-3]):[0-5]\d$/.test(d.time)&&typeof d.zone==='string';
 try{const raw=localStorage.getItem(key);if(raw){const parsed=JSON.parse(raw);if(!Array.isArray(parsed)||parsed.length>50||!parsed.every(valid))throw Error();drafts=parsed;}}catch{$('routine-notice').textContent='Saved plan drafts could not be read. New drafts can still be prepared.';}
 for(const [id,label]of Object.entries(apps)){const l=n('label',''),i=document.createElement('input');i.type='checkbox';i.value=id;i.dataset.routineApp=id;l.append(i,n('span',label));$('routine-apps').append(l);}
 const checks=()=>document.querySelectorAll('[data-routine-app]');
 function summary(d){return `${{daily:'Every day',weekdays:'Weekdays',weekly:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][Number(d.day)]}[d.frequency]} · ${d.time} · ${d.zone}`;}
 function list(){$('routine-list').replaceChildren();if(!drafts.length){$('routine-list').append(n('strong','Your saved plans appear here'),n('p','Choose a starting point or write your own plan.'));}for(const d of drafts){const button=b(d.name,()=>edit(d));button.append(n('small','Draft · Not scheduled'));$('routine-list').append(button);}}
 function home(){$('routine-hub').hidden=false;$('routine-editor').hidden=true;$('routine-preview-panel').hidden=true;editing=null;}
 function edit(d){editing=d.id||null;$('routine-hub').hidden=true;$('routine-editor').hidden=false;$('routine-preview-panel').hidden=true;$('routine-editor-title').textContent=editing?'Edit your plan':'Make this plan yours';$('routine-name').value=d.name||'';$('routine-prompt').value=d.prompt||'';$('routine-frequency').value=d.frequency||'weekdays';$('routine-time').value=d.time||'09:00';$('routine-day').value=d.day||'5';$('routine-day-field').hidden=$('routine-frequency').value!=='weekly';$('routine-zone').value=d.zone||Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';$('routine-consent').checked=!!editing;$('routine-delete').hidden=!editing;for(const c of checks())c.checked=(d.apps||[]).includes(c.value);$('routine-notice').textContent='';$('routine-name').focus();}
 function read(){const d={id:editing||crypto.randomUUID(),name:$('routine-name').value.trim(),prompt:$('routine-prompt').value.trim(),apps:Array.from(checks()).filter(c=>c.checked).map(c=>c.value),frequency:$('routine-frequency').value,day:$('routine-day').value,time:$('routine-time').value,zone:$('routine-zone').value.trim()};if(!valid(d)||!d.name||d.prompt.length<10||!d.apps.length)throw Error('Add a name, a prompt of at least 10 characters, a valid time, and at least one app.');try{new Intl.DateTimeFormat('en',{timeZone:d.zone}).format();}catch{throw Error('Enter a valid timezone, such as America/New_York or Europe/London.');}return d;}
 function preview(d){const p=$('routine-preview-panel');p.replaceChildren(n('strong',d.name),n('p',d.prompt),n('p',d.apps.map(a=>apps[a]).join(' · ')),n('p','Preferred schedule: '+summary(d)),n('p','Draft only. No next run is scheduled. Activation will require connected apps and the scheduling service.'));p.hidden=false;}
 for(const t of templates){const card=n('article','','routine-template'),top=n('div','','panel-top');top.append(n('span',t[6],'app-symbol'),n('span',({weekdays:'Weekdays',daily:'Every day',weekly:'Weekly'})[t[4]]+' · '+t[5],'badge'));card.append(top,n('h3',t[0]),n('p',t[1]));const tags=n('div','','routine-tags');for(const a of t[3])tags.append(n('span',apps[a]));card.append(tags,b('Customize this plan →',()=>edit({name:t[0],prompt:t[2],apps:t[3],frequency:t[4],time:t[5]})));$('routine-templates').append(card);}
 $('routine-home').addEventListener('click',home);$('routine-back').addEventListener('click',home);$('routine-new').addEventListener('click',()=>edit({}));$('routine-frequency').addEventListener('change',()=>{$('routine-day-field').hidden=$('routine-frequency').value!=='weekly';});
 $('routine-preview').addEventListener('click',()=>{try{preview(read());$('routine-notice').textContent='Review your instructions and preferred schedule below. No messages have been read or generated.';}catch(e){$('routine-notice').textContent=e.message;}});
 $('routine-form').addEventListener('submit',e=>{e.preventDefault();try{const d=read();if(!$('routine-consent').checked)throw Error('Confirm browser storage before saving.');if(!editing&&drafts.length>=50)throw Error('You have 50 drafts. Edit or delete one before adding another.');const next=editing?drafts.map(x=>x.id===editing?d:x):[d,...drafts];localStorage.setItem(key,JSON.stringify(next));drafts=next;editing=d.id;$('routine-delete').hidden=false;list();preview(d);$('routine-notice').textContent='Plan draft saved on this browser. It will not run automatically.';}catch(e){$('routine-notice').textContent=e.name==='QuotaExceededError'?'Browser storage is full. Your draft has not been saved.':e.message;}});
 $('routine-delete').addEventListener('click',()=>{if(!editing)return;if(!window.confirm('Delete this plan draft from this browser?'))return;try{const next=drafts.filter(d=>d.id!==editing);localStorage.setItem(key,JSON.stringify(next));drafts=next;home();list();$('routine-notice').textContent='Plan draft deleted.';}catch{$('routine-notice').textContent='The draft could not be deleted. Please try again.';}});
 list();
})();
